#!/usr/bin/env python3
"""Write per-work metadata.json files into /nas/ucb/eeshan/digitization_queue/<slug>/.

Reads _fetch_summary.json for each work and merges in hand-curated bibliographic
fields from docs/ACQUISITION_PATHWAYS.md §A.
"""
from __future__ import annotations

import json
from pathlib import Path

QUEUE = Path("/nas/ucb/eeshan/digitization_queue")
TODAY = "2026-05-19"
AGENT = "corpus-chat-lane3"

# Hand-curated per-work bibliographic and engagement metadata, drawn from
# docs/ACQUISITION_PATHWAYS.md §A prose.
WORKS = {
    "baladeva_govinda_bhasya": {
        "work_title_iast": "Govinda-Bhāṣya",
        "thinker_id": "baladeva",
        "edition": "Kṛṣṇadāsa Bābā 1965 edition (Vikrama Saṃvat 2022); Sanskrit text with Hindi anvaya and translation",
        "year": "1965",
        "editor": "Kṛṣṇadāsa Bābā",
        "publisher": "Kṛṣṇadāsa Bābā / Kusum Sarovar, Vraja",
        "language_primary": "sanskrit",
        "secondary_languages": ["hindi"],
        "script": "devanagari",
        "commentaries_included": ["anvaya-and-Hindi-translation-by-Krsnadasa-Baba"],
        "source_url": "https://archive.org/details/GovindaBhasya.KrsnadasBaba",
        "source_item_id": "GovindaBhasya.KrsnadasBaba",
        "license": "public_domain",
        "expected_text_units": {"kind": "sutras", "approximate_count": 555,
            "source_for_estimate": "Brahma-Sūtra canonical count (4 chapters × 4 pādas × variable adhikaraṇas; standard total 555)"},
        "ground_truth_available": True,
        "ground_truth_source": "GRETIL Brahma-Sūtra mūla and Govinda-Bhāṣya Sanskrit transcriptions for spot-comparison; Bhanu Swami 2018 English (ISBN 978-1-980-71071-4) for sense-checking",
        "first_page_visual_quality": "heavy_bleed",
        "first_page_visual_quality_notes": "Heuristic (KB/page ~170): mid-range scan. Producer 'PDFArea Image to PDF Converter' suggests post-processed page images — typical OCR-friendliness moderate.",
        "ocr_friendliness_notes": "Image-PDF assembled from page scans; expect standard Devanagari OCR difficulties (saṃyukta-akṣaras, mātrā-on-mātrā). Hindi anvaya rows below the Sanskrit mūla complicate line segmentation.",
        "priority_tier": "A1",
        "ocr_notes_phase2": "Will need column/region masking to separate Sanskrit mūla from Hindi anvaya.",
    },
    "bhaskara_brahma_sutra_bhasya": {
        "work_title_iast": "Brahma-Sūtra-Bhāṣya",
        "thinker_id": "bhaskara",
        "edition": "Chowkhamba Sanskrit Series Nos. 70, 185, 209, Banaras 1903–1915 (Vindhyeśvarī Prasāda Dvivedī)",
        "year": "1915",
        "editor": "Vindhyeśvarī Prasāda Dvivedī",
        "publisher": "Chowkhamba Sanskrit Series, Banaras",
        "language_primary": "sanskrit",
        "secondary_languages": [],
        "script": "devanagari",
        "commentaries_included": [],
        "source_url": "https://archive.org/details/BrahmaSutraBhashyaOfBhaskarNos.70185209Year1915ChowkhambaSanskritSeries",
        "source_item_id": "BrahmaSutraBhashyaOfBhaskarNos.70185209Year1915ChowkhambaSanskritSeries",
        "license": "public_domain",
        "expected_text_units": {"kind": "sutras", "approximate_count": 555,
            "source_for_estimate": "Brahma-Sūtra canonical count; Bhāskara comments on the standard 555-sūtra sequence"},
        "ground_truth_available": False,
        "ground_truth_source": "No mature digital comparator for Bhāskara's bhāṣya text; partial GRETIL fragments only.",
        "first_page_visual_quality": "moderate_bleed",
        "first_page_visual_quality_notes": "Heuristic (KB/page ~286): standard Chowkhamba 1915 typesetting. Adobe PDF Scan Library producer; expect typical archive.org Devanagari scan with some half-tone bleed.",
        "ocr_friendliness_notes": "Clean Devanagari typeset, single-column. Should be one of the OCR-friendliest texts in the priority-12.",
        "priority_tier": "A2",
    },
    "citsukha_tattva_pradipika": {
        "work_title_iast": "Tattva-Pradīpikā (Cit-Sukhī)",
        "thinker_id": "citsukha",
        "edition": "Nirṇayasāgara Press 1931, ed. Raghunātha Kāśīnātha Śāstrī, with Nayana-Prasādinī commentary of Pratyagsvarūpa-Bhagavān",
        "year": "1931",
        "editor": "Raghunātha Kāśīnātha Śāstrī",
        "publisher": "Nirṇayasāgara Press, Mumbai",
        "language_primary": "sanskrit",
        "secondary_languages": [],
        "script": "devanagari",
        "commentaries_included": ["Nayana-Prasādinī (Pratyagsvarūpa-Bhagavān)"],
        "source_url": "https://archive.org/details/SKEw_tattva-pradipika-chitsukhi-of-chitsukhacharya-with-commentary-nayana-prasadini-b",
        "source_item_id": "SKEw_tattva-pradipika-chitsukhi-of-chitsukhacharya-with-commentary-nayana-prasadini-b",
        "license": "public_domain",
        "expected_text_units": {"kind": "paragraphs", "approximate_count": 400,
            "source_for_estimate": "Four paricchedas across 412 pages; ground-truth count via Phase 2 segmentation"},
        "ground_truth_available": False,
        "ground_truth_source": "No mature digital comparator; SARIT and GRETIL hold partial texts only.",
        "first_page_visual_quality": "clean",
        "first_page_visual_quality_notes": "Heuristic (KB/page ~560): high-DPI scan. Producer 'BookChanger 4.6.3' typical of recent high-quality archive.org uploads.",
        "ocr_friendliness_notes": "Nirṇayasāgara 1931 typesetting is among the cleanest of pre-WWII Sanskrit printing. Two-text layout (mūla + Nayana-Prasādinī) requires region segmentation.",
        "priority_tier": "A3",
    },
    "jayatirtha_tattva_prakashika": {
        "work_title_iast": "Tattva-Prakāśikā",
        "thinker_id": "jayatirtha",
        "edition": "UNVERIFIED — uploader-attributed PDF, edition not stated on archive.org metadata page; uploader SrihariPKurudi (2022); requires visual inspection before citation as Panchamukhi 1980–1981 or any other named edition",
        "edition_verification_required": True,
        "year": "unknown",
        "editor": "unknown",
        "publisher": "unknown",
        "language_primary": "sanskrit",
        "secondary_languages": [],
        "script": "devanagari",
        "commentaries_included": [],
        "source_url": "https://archive.org/details/tattva-prakasika",
        "source_item_id": "tattva-prakasika",
        "license": "unclear",
        "expected_text_units": {"kind": "paragraphs", "approximate_count": 555,
            "source_for_estimate": "Sub-commentary on Madhva BSB; one tattva-prakāśikā gloss per BSB sūtra ≈ 555"},
        "ground_truth_available": False,
        "ground_truth_source": "Pending edition verification.",
        "first_page_visual_quality": "born_digital_text_likely",
        "first_page_visual_quality_notes": "Heuristic (KB/page ~3): producer 'Acrobat Distiller 8.0.0' + 897 KB / 328 pp suggests a *born-digital text PDF*, not a scan. If so, this is ideal for OCR (or pdftotext would suffice). Visual confirmation is the open question, not OCR-difficulty.",
        "ocr_friendliness_notes": "Almost certainly text-PDF (not image-PDF); pdftotext or copy-paste will yield clean Sanskrit. Still requires edition identification before any quotation can be made.",
        "priority_tier": "A4",
        "ocr_status_special": "pdf_pending_edition_id",
    },
    "madhusudana_gudhartha_dipika": {
        "work_title_iast": "Gūḍhārtha-Dīpikā on the Bhagavad-Gītā",
        "thinker_id": "madhusudana",
        "edition": "Advaita Ashrama (Belur Math) edition, Swami Gambhirananda, *Bhagavadgītā with the Annotation Gūḍhārtha-Dīpikā*, 1998 (Sanskrit + English)",
        "year": "1998",
        "editor": "Swami Gambhirananda",
        "publisher": "Advaita Ashrama, Calcutta",
        "language_primary": "sanskrit",
        "secondary_languages": ["english"],
        "script": "devanagari",
        "commentaries_included": ["English translation and notes by Swami Gambhirananda"],
        "source_url": "https://archive.org/details/tDyP_bhagavad-gita-with-gudharth-deepika-by-madhusudan-sarasvati-translated-by-swami-",
        "source_item_id": "tDyP_bhagavad-gita-with-gudharth-deepika-by-madhusudan-sarasvati-translated-by-swami-",
        "license": "public_domain",
        "expected_text_units": {"kind": "verses", "approximate_count": 700,
            "source_for_estimate": "Bhagavad-Gītā canonical 700 ślokas, each with Madhusūdana's gloss"},
        "ground_truth_available": True,
        "ground_truth_source": "Embedded English translation by Gambhirananda is itself a high-quality bilingual comparator; GRETIL Gītā mūla provides verse-level ground truth.",
        "first_page_visual_quality": "clean",
        "first_page_visual_quality_notes": "Heuristic (KB/page ~466): high-DPI scan. Producer 'BookChanger 4.6.3'. 1052 pages of clean Advaita Ashrama typesetting.",
        "ocr_friendliness_notes": "Bilingual Sanskrit/English layout requires script-detection and region masking. The Sanskrit Devanagari portion is typical Belur Math house style — clean. English portion is straightforward Latin OCR.",
        "priority_tier": "A5",
    },
    "madhva_gita_tatparya_nirnaya": {
        "work_title_iast": "Gītā-Tātparya-Nirṇaya",
        "thinker_id": "madhva",
        "edition": "D. Prahlādācar (ed.), *Gītā-Tātparya-Nirṇaya of Ānandatīrtha-Bhagavatpādācārya, with the Nyāya-Dīpikā of Jayatīrtha and the Bhāva-Dīpa of Raghavendra-tīrtha*, Pūrṇaprajña Saṃśodhana Mandiram, Bangalore, 1987",
        "year": "1987",
        "editor": "D. Prahlādācar",
        "publisher": "Pūrṇaprajña Saṃśodhana Mandiram, Bangalore",
        "language_primary": "sanskrit",
        "secondary_languages": [],
        "script": "devanagari",
        "commentaries_included": ["Nyāya-Dīpikā (Jayatīrtha)", "Bhāva-Dīpa (Rāghavendra-tīrtha)"],
        "source_url": "https://archive.org/details/anandatirthabhagavatpadacharyavirachitahgitatatparyanirnayaheditedbydprahladachar1987",
        "source_item_id": "anandatirthabhagavatpadacharyavirachitahgitatatparyanirnayaheditedbydprahladachar1987",
        "license": "public_domain",
        "expected_text_units": {"kind": "verses", "approximate_count": 700,
            "source_for_estimate": "Madhva's prose tātparya-comments running through the Gītā's 700 ślokas plus three sub-commentaries"},
        "ground_truth_available": True,
        "ground_truth_source": "Nagesh D. Sonde Sanskrit+English (archive.org `geeta-bhashya-tatparya-nirnaya-by-madhvacharya`) is a comparator for sense; Madhwapracharavedike has the Bannañje edition for textual cross-check.",
        "first_page_visual_quality": "born_digital_text_likely",
        "first_page_visual_quality_notes": "Heuristic (KB/page ~29): producer 'PDFsharp 1.50.4589' + 10.6 MB / 371 pp suggests a born-digital text or near-text PDF, not a high-DPI scan. Likely ideal for direct text extraction.",
        "ocr_friendliness_notes": "If born-digital, pdftotext-grade. If image-PDF, low-DPI 1987 typescript — expect moderate OCR difficulty. Three commentaries stacked on one page require careful region segmentation.",
        "priority_tier": "A7",
    },
    "suresvara_brhadaranyaka_varttika": {
        "work_title_iast": "Bṛhadāraṇyaka-Upaniṣad-Bhāṣya-Vārttikam",
        "thinker_id": "sureshvara",
        "edition": "K.S. Āgāśe, *Bṛhadāraṇyaka-Upaniṣad-Bhāṣya-Vārttikam of Sureśvarācārya with the Śāstra-Prakāśikā of Ānandagiri*, Ānandāśrama Sanskrit Series No. 16, 3 vols., Pune, 1892–1893 (reprinted 1937). Single PDF item bundles all three volumes.",
        "year": "1892–1893 (reprinted 1937)",
        "editor": "K.S. Āgāśe",
        "publisher": "Ānandāśrama Press, Pune",
        "language_primary": "sanskrit",
        "secondary_languages": [],
        "script": "devanagari",
        "commentaries_included": ["Śāstra-Prakāśikā (Ānandagiri)", "Śaṅkara's Bṛhadāraṇyaka-Bhāṣya (the base text Sureśvara is vārttika-ing)"],
        "source_url": "https://archive.org/details/BrihadaranyakaBhashyaVartikam2",
        "source_item_id": "BrihadaranyakaBhashyaVartikam2",
        "license": "public_domain",
        "expected_text_units": {"kind": "varttikas", "approximate_count": 11550,
            "source_for_estimate": "Sureśvara's BUBV has 11,550 vārttikas (Hiriyanna count); 968-page PDF aligns"},
        "ground_truth_available": True,
        "ground_truth_source": "A.J. Alston, *Realisation of the Absolute* (8 vols, Shanti Sadan 1989–1996) — full English vehicle, secondhand only; partial GRETIL fragments.",
        "first_page_visual_quality": "compressed_legible",
        "first_page_visual_quality_notes": "Heuristic (KB/page ~52): low-bitrate JPEG2000 compression — typical of Adobe Acrobat 9.0 Image Conversion archive uploads. The KB/page proxy under-reads quality here; Anandashram 1892 typesetting is renowned for clarity. Expect *legible* scan despite small file size.",
        "ocr_friendliness_notes": "Three commentaries (Śaṅkara mūla-bhāṣya, Sureśvara vārttika, Ānandagiri ṭīkā) on a single page is the *worst* region-segmentation challenge in the priority-12. Reference: Anandashram three-column format with vārttika numbering. Will require trained layout model.",
        "priority_tier": "A9",
    },
    "suresvara_taittiriya_varttika": {
        "work_title_iast": "Taittirīya-Upaniṣad-Bhāṣya-Vārttikam",
        "thinker_id": "sureshvara",
        "edition": "Ānandāśrama Sanskrit Series No. 13, *Taittirīya-Upaniṣad-Vārttika-Bhāṣya with Tīkā by Sureśvarācārya*, Pune, 1889",
        "year": "1889",
        "editor": "Anandashram editorial board",
        "publisher": "Ānandāśrama Press, Pune",
        "language_primary": "sanskrit",
        "secondary_languages": [],
        "script": "devanagari",
        "commentaries_included": ["Ānandagiri's Tīkā", "Śaṅkara's Taittirīya-Bhāṣya (base)"],
        "source_url": "https://archive.org/details/gOtp_taitiriya-upanishad-bhashya-vartika-by-sureshvara-acharya-1889-anand-ashram-press",
        "source_item_id": "gOtp_taitiriya-upanishad-bhashya-vartika-by-sureshvara-acharya-1889-anand-ashram-press",
        "license": "public_domain",
        "expected_text_units": {"kind": "varttikas", "approximate_count": 1100,
            "source_for_estimate": "Sureśvara's TUBV has roughly 1100 vārttikas across the three vallīs of the Taittirīya"},
        "ground_truth_available": True,
        "ground_truth_source": "R. Balasubramanian, *The Taittirīyopaniṣad-Bhāṣya-Vārttika of Sureśvara* (Madras 1974) — full English with Sanskrit base; PDF at archive.org `taittiriyavartika` and centreforbrahmavidya.org.",
        "first_page_visual_quality": "clean",
        "first_page_visual_quality_notes": "Heuristic (KB/page ~906): exceptional high-DPI scan. Producer 'BookChanger 4.6.3'. 225 pages.",
        "ocr_friendliness_notes": "Three-text Anandashram layout (Śaṅkara base + Sureśvara vārttika + Ānandagiri ṭīkā) is the same region-segmentation challenge as BUBV, but a much smaller corpus and a much cleaner scan. Better OCR development target than BUBV.",
        "priority_tier": "A10",
    },
    "vidyaranya_vivarana_prameya_sangraha": {
        "work_title_iast": "Vivaraṇa-Prameya-Saṃgraha",
        "thinker_id": "vidyaranya",
        "edition": "Parasanātha Dvivedī (ed.), *Vivaraṇa-Prameya-Saṅgraha of Vidyāraṇya-Muni*, Sampūrṇānanda Saṃskṛta Viśvavidyālaya, Varanasi, 2005 (Sanskrit + Hindi)",
        "year": "2005",
        "editor": "Parasanātha Dvivedī",
        "publisher": "Sampūrṇānanda Saṃskṛta Viśvavidyālaya, Varanasi",
        "language_primary": "sanskrit",
        "secondary_languages": ["hindi"],
        "script": "devanagari",
        "commentaries_included": ["Hindi anvaya and translation by Parasanātha Dvivedī"],
        "source_url": "https://archive.org/details/fzFh_vivarana-prameya-sangraha-by-vidyaranya-muni-edited-by-parasa-nath-dvivedi-2005-",
        "source_item_id": "fzFh_vivarana-prameya-sangraha-by-vidyaranya-muni-edited-by-parasa-nath-dvivedi-2005-",
        "license": "public_domain",
        "expected_text_units": {"kind": "paragraphs", "approximate_count": 800,
            "source_for_estimate": "Eight sections (varṇakas) of Vidyāraṇya's Vivaraṇa-summary, with the 2005 critical edition running 946 pages including Hindi"},
        "ground_truth_available": False,
        "ground_truth_source": "Existing 1893 Vizianagaram PDF on corpus disk is a comparator but is the *degraded* version this acquisition is meant to *replace* (see ACQUISITION_PATHWAYS §C.1).",
        "first_page_visual_quality": "clean",
        "first_page_visual_quality_notes": "Heuristic (KB/page ~533): high-DPI scan. Producer 'BookChanger 4.6.3'. 946 pages. 2005 typesetting is born-digital quality.",
        "ocr_friendliness_notes": "2005 critical edition with modern typesetting — by far the most OCR-friendly Sanskrit/Hindi pair in the priority-12. Hindi anvaya rows require script-region segmentation but are likely well-separated from the Sanskrit mūla.",
        "priority_tier": "A12",
        "ocr_notes_phase2": "Highest-priority replacement target per ACQUISITION_PATHWAYS §C.1.",
    },
}


def main():
    for slug, fields in WORKS.items():
        work_dir = QUEUE / slug
        fetch = json.load(open(work_dir / "_fetch_summary.json"))
        rec = fetch["pdf_records"][0]
        info = rec["pdfinfo"]

        meta = {
            "work_slug": slug,
            **fields,
            "downloaded_at": TODAY,
            "downloaded_by": AGENT,
            "sha256": rec["sha256"],
            "size_bytes": rec["size_bytes"],
            "pdfinfo": {
                "pages": info.get("pages"),
                "page_size": info.get("page_size"),
                "encrypted": info.get("encrypted"),
                "linearized": None,  # pypdf doesn't expose this directly
                "producer": info.get("producer"),
                "creator": info.get("creator"),
                "title": info.get("title"),
            },
            "ocr_friendliness_score": rec["ocr_friendliness_score"],
            "ia_filename": rec["ia_filename"],
            "_acquisition_lane": "lane3-digitization-prep",
            "_phase2_ocr_status": "not_started",
        }

        out_path = work_dir / "metadata.json"
        out_path.write_text(json.dumps(meta, indent=2, ensure_ascii=False))
        print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
